### ISSUE TITLE
Shell script task : s3 cp sets incorrect `Content-Type` metadata

### ISSUE THREAD

**Issue by strvngwvs** [aws/aws-toolkit-azure-devops#394]
**Bug description**

_aws s3 cp_ command sets Content-Type to 'binary/octet-stream' while setting additional metadata.

**Reproducing scenario**

Here's a setup of the corresponding task:
```YAML
task: AWSShellScript@1
displayName: Set caching headers on S3 bucket files
inputs:
  awsCredentials: '${{ parameters.Credentials }}'
  regionName: ...
  scriptType: 'inline'
  inlineScript: |
    aws s3 cp s3://$bucketNameParam/ s3://$bucketNameParam/ --metadata-directive REPLACE --cache-control no-store --recursive --exclude "*" --include "*.html" --include "*.json"`
```

The task is executed on Azure hosted agents.

**Expected behavior**

_Content-Type_ metadata remains original / is determined correctly while copying witout passing it explicitly

**My Environment**

-   Cloud-based
-   AWS Toolkit for Azure DevOps version: 1.9.0

**Additional context**

This setup used to work as expected before and worked correctly for quite a long time after update to 1.9.0 version.
The problem is also reproduceable with latest version of aws-cli (2.1.27), while, for example, with 1.18.7 everything works correctly.
