### ISSUE TITLE
Allow the s3 upload task to set metadata (x-amz-meta-) values

### ISSUE THREAD

**Issue by jlamhp** [aws/aws-toolkit-azure-devops#405]
**Is your feature request related to a problem? Please describe.**

The current s3 upload task does not allow the ability to set x-amz-meta values. Currently we would be forced to use the cli to do this.

**Describe the solution you'd like**

An additional optional parameter that takes in an array or map of meta values to set for the object(s) being uploaded
Example:
```
- task: AmazonWebServices.aws-vsts-tools.S3Upload.S3Upload@1
  inputs:
    ....
    metadata:
    - version: "1.2.3.4"
    - customname: customvalue
 
```
Above command should result in the s3 objects with x-amz-meta-version set to 1.2.3.4 and x-amz-meta-customname to customvalue

Note: I don't know how the above should be property formatted or if there's a better way to do this, however it should operate like the  --metadata option in the cli.

**Describe alternatives you've considered**

We can use the cli to do this, but would prefer to be able to use to the packaged task to make the code more simple.
