### ISSUE TITLE
Are Inline defined Parameter types in Azure DevOps Pipeline cofngiruation, correctly passed in to CloudFormationCreateOrUpdateStack@1?

### ISSUE THREAD

**Issue by JDTAY** [aws/aws-toolkit-azure-devops#410]
Are Inline defined Parameter types in Azure DevOps Pipeline configuration, correctly passed in to CloudFormationCreateOrUpdateStack@1?

Parameters defined as string and numbers in pipelines, as an example refer to the below code block, are erroring with: 

`##[error]InvalidParameterType: Expected params.Parameters[1].ParameterValue to be a string`

I don't know if the Azure Pipelines service is losing/incorrectly specifying the incorrect parameter type here, or if the AWS Toolkit is not parsing the inputs correctly. 

I've attached the full error output from this step (refer to step.log). 
[step.log](https://github.com/aws/aws-toolkit-azure-devops/files/6463218/step.log)

Inline parameters:

```yaml
parameters:
- name: SubnetCidrBits
  displayName: SubnetCidrBits
  type: number
  default: 13
  values:
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
- name: VpcCidr
  displayName: VpcCidr
  type: string
  default: '172.16.0.0/16'
```

CloudFormation task:

```yaml

    - task: CloudFormationCreateOrUpdateStack@1
      inputs:
        awsCredentials: 'AWSToolkit'
        regionName: "ap-southeast-2"
        stackName: ${{ parameters.RegionPrefix }}${{ parameters.CustomerTag }}${{ parameters.EnvironmentTag }}${{ parameters.StackInteger }}-Platform-VPC
        templateSource: 's3'
        s3BucketName: $(BucketName)
        s3ObjectKey: $(System.TeamProject)/$(Build.SourceBranchName)/2-ci-cd-network/deploy/vpc.cf.yml
        # templateParametersFile: './2-ci-cd-network/parameters/development-parameters.yml' use this parameter if you want to use a local file
        templateParametersSource: 'inline'
        templateParameters: |
          - ParameterKey: InfrastructureReleaseTag
            ParameterValue: ${{ parameters.InfrastructureReleaseTag }}
          - ParameterKey: SubnetCidrBits
            ParameterValue: ${{ parameters.SubnetCidrBits }}
          - ParameterKey: VpcCidr
            ParameterValue: ${{ parameters.VpcCidr }}
          - ParameterKey: EnvironmentTag
            ParameterValue: ${{ parameters.EnvironmentTag }}'
          - ParameterKey: CustomerTag
            ParameterValue: ${{ parameters.CustomerTag }}
          - ParameterKey: ServiceLayerTag
            ParameterValue: ${{ parameters.ServiceLayerTag }}
        tags: |
          EnvironmentTag=${{ parameters.EnvironmentTag }}
          CustomerTag=${{ parameters.CustomerTag }}
          InfrastructureReleaseTag=${{ parameters.InfrastructureReleaseTag }}
          ServiceLayerTag=${{ parameters.ServiceLayerTag }}
        disableRollback: DisableRollback
        outputVariable: ${{ parameters.RegionPrefix }}${{ parameters.CustomerTag }}${{ parameters.EnvironmentTag }}${{ parameters.StackInteger }}-Platform-VPC
 ```

Setting these parameters inline of the pipeline are spitting out errors during runtime. If I explicitly define the parameters in a file rather than inline. I don't see the same problems: 

Use this parameter in the CloudFormation step:
 
 * TemmplateParametersFile: './2-ci-cd-network/parameters/development-parameters.yml' 
 
Contents:
 
 ```yaml
 ---
- ParameterKey: InfrastructureReleaseTag
  ParameterValue: '1.0.0'
- ParameterKey: SubnetCidrBits
  ParameterValue: '13'
- ParameterKey: VpcCidr
  ParameterValue: '172.168.16.0/16'
- ParameterKey: EnvironmentTag
  ParameterValue: 'DV'
- ParameterKey: CustomerTag
  ParameterValue: 'IN'
- ParameterKey: ServiceLayerTag


  ParameterValue: 'FabricLayer'
  ```
  
 Rather than use what I captured above, I don't see the same problems. 
 
 I've attached my full pipeline if you'd like to peruse over it, though I haven't included the related CloudFormation template:
[dev-azure-pipeline.txt](https://github.com/aws/aws-toolkit-azure-devops/files/6463233/dev-azure-pipeline.txt)
