### ISSUE TITLE
Using a non-inline script with AWS Shell Script

### ISSUE THREAD

**Issue by ck3mp** [aws/aws-toolkit-azure-devops#425]
Searched for a while but cannot find any clear instructions on how to use a non-inline script?

Tried using this but the options aren't specified well.
https://docs.aws.amazon.com/vsts/latest/userguide/awsshell.html

When using this:

```
      - task: AWSShellScript@1
        displayName: "Environment Setup"
        inputs:
          awsCredentials: ${{ parameters.serviceConnection }}
          scriptType: file
          scriptPath: DevOps/scripts/Environment_Setup.sh
```

The pipleline just hangs until the timeout is hit. I can see the contents of the script from a Bash component with the same inputs.
