### ISSUE TITLE
CDK bootstrapping fail, unable to parse environment specification

### ISSUE THREAD

**Issue by Fitmavincent** [aws/aws-toolkit-azure-devops#444]
**CDK bootstrap fail, unable to parse environment specification using AWSShellScript@1**

**Reproduction**

1. Prepare a pipeline script for ```cdk bootstrap```
e.g.
```yml
- task: AWSShellScript@1
      inputs:
        awsCredentials: 'prod'
        regionName: 'ap-southeast-2'
        scriptType: 'inline'
        inlineScript: |
          echo "Bootstrapping environment"
          cdk bootstrap aws://$(ACCOUNT)/$(REGION)

      displayName: 'Deploying Project Infrastructure on Production'
```
2. Run the pipeline

**Expected behavior**

It should be able to go through the bootstrapping process without errors as awsCredentials, account and regions specification provided

![image](https://user-images.githubusercontent.com/7020812/142334696-9ef7af6e-7df0-4f4e-a5d5-1949048e1eaf.png)

However, after aws shell script task upgrade to 1.11.0, it no longer be able to cdk bootstrap and keep throwing errors on **unable to parse environment specification**

![image](https://user-images.githubusercontent.com/7020812/142334497-73c739fb-0589-4374-b929-cdf876be96fe.png)

**Your Environment**

-   On-prem or cloud based?: Cloud base
-   Azure DevOps version: Version Dev18.M194.1 (AzureDevOps_M194_20211112.8)
-   AWS Toolkit for Azure DevOps version: AWS CDK latest
