### ISSUE TITLE
IllegalLocationConstraintException when create S3 bucket

### ISSUE THREAD

**Issue by linfengslalom** [aws/aws-toolkit-azure-devops#450]
I am using task `S3Upload@1` in my yaml running in Azure DevOps.
When I set `createBucket` to `true` as below:

```
- task: S3Upload@1
  inputs:
    awsCredentials: testserviceconnection
    regionName: us-east-1
    bucketName: somethingtest
    sourceFolder: cfntest
    globExpressions: '**'
    targetFolder: clientlambda
    createBucket: true
```

I got an error as below:

```
message: 'The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.',
code: 'IllegalLocationConstraintException',
region: null,
```

I think except bucketName, LocationConstraint should be set as well? Regarding the issue https://github.com/aws/aws-sdk-js/issues/475

https://github.com/aws/aws-toolkit-azure-devops/blob/6590be0558e2bd45cb4fb873be0f5616a7cac769/src/tasks/S3Upload/TaskOperations.ts#L63
