### ISSUE TITLE
AWSShellScript@1 file not found when specifying workingDirectory

### ISSUE THREAD

**Issue by sreeprasadn** [aws/aws-toolkit-azure-devops#488]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Your Environment**

-   On-prem or cloud based?:  Azure DevOps
-   Azure DevOps version:
-   AWS Toolkit for Azure DevOps version: 1.13.0

**Additional context**

**Comment by lareeth** [comment]
Can you trying adding `disableAutoCwd: true` to your `AWSShellScript@1` task properties, otherwise the `workingDirectory` property is ignored

```
  - task: AWSShellScript@1
    displayName: 'Functional Test'
    inputs:
      awsCredentials: 'terraform-azuredevops-development'
      regionName: 'eu-central-1'
      scriptType: 'filePath'
      arguments: '${{parameters.branch}} ${{parameters.validation}} ${{parameters.dataflow}} ${{parameters.iterations}} $(case1) $(case2) $(case3) $(case4)'
      filePath: ./functional-test.sh
      disableAutoCwd: true
      workingDirectory: '$(System.DefaultWorkingDirectory)/temp/'
```
