### ISSUE TITLE
dotnet 6 app now giving error: "Command hooks failed" when deploying

### ISSUE THREAD

**Issue by gotmike** [aws/aws-toolkit-azure-devops#492]
My prior pipeline quit working with dotnet 6 deployment to elastic beanstalk.

I have found this guide --> https://docs.aws.amazon.com/vsts/latest/userguide/tutorial-eb.html

Following these steps which use `msbuild` instead of `dotnet build` seem to work but deployment to elastic beanstalk fails with a new error I have not seen before: `Error occurred during build: Command hooks failed`

**To reproduce**

YAML for the deployment tasks looks like this...

```
  - task: NuGetToolInstaller@1
    displayName: Use NuGet 5.x
    inputs:
      versionSpec: 5.x
      checkLatest: true
  - task: NuGetCommand@2
    displayName: NuGet restore
    inputs:
      noCache: true
  - task: VSBuild@1
    displayName: Build Project
    inputs:
      solution: AppName/AppName/AppName.csproj
      msbuildArgs: /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactstagingdirectory)\WebApp_$(build.BuildId).zip" /p:DeployIisAppPath="Default Web Site"
      platform: x64
      configuration: release
      clean: true
      msbuildArchitecture: x64
  - task: BeanstalkDeployApplication@1
    displayName: 'Deploy to Elastic Beanstalk: AppName'
    inputs:
      awsCredentials: 63ff2436-14ff-4391-836c-c14f27af9473
      regionName: us-east-1
      applicationName: AppName
      environmentName: appname-dev
      webDeploymentArchive: $(build.artifactstagingdirectory)\WebApp_$(build.BuildId).zip
      dotnetPublishPath: $(build.artifactstagingdirectory)\WebApp_$(build.BuildId).zip
      versionLabel: 'Azure DevOps Build Id: $(build.buildid)'
      description: $(Build.SourceVersionMessage)
```

**Expected behavior**

Deploy cleanly without errors

**Screenshots**

![image](https://user-images.githubusercontent.com/4323261/205282012-8ac5294d-af83-4ecf-9ae7-580186d25010.png)

**Your Environment**

- Azure DevOps
- Elastic Beanstalk: IIS 10.0 running on 64bit Windows Server Core 2019/2.10.6
- Region: us-east-1
- Code: dotnet 6
