### ISSUE TITLE
env section for AWSShellScript@1

### ISSUE THREAD

**Issue by vasily-kartashov** [aws/aws-toolkit-azure-devops#594]
At the moment the only way of passing variables to an external script is through arguments, which is rather clunky:

```yaml
steps:
  - task: AWSShellScript@1
    inputs:
      ...
      arguments: "$(Build.SourcesDirectory) $(AWSAccountID) $(AWSRegion) $(PythonVersion)"
      filePath: pipelines/scripts/quality-assurance.sh
```

with the consumer being:

```bash
#!/usr/bin/env sh

set -eou pipefail

SourcesDirectory="${1:?}"
AWSAccountID="${2:?}"
AWSRegion="${3:?}"
PythonVersion="${4:?}"
```

Even here, there's no guarantee for the parameters to be in the right order, whereas simple

```yaml
```yaml
steps:
  - task: AWSShellScript@1
    inputs:
      env:
         SourceDirectory: $(Build.SourcesDirectory)
         ...
      filePath: pipelines/scripts/quality-assurance.sh
```

Would have resolved the issue.
